[package]
name = "entity"
version = "0.0.0"
edition = "2021"

[dependencies.bevy]
version = "0.7.0"
default-features = false

[dependencies]
bevy_renet = "0.0.4"
bincode = "1.3.3"
serde = {version= "1.0.137"}

networking = { path = "../networking" }
health = { path = "../health" }
pawn = { path = "../pawn" }
api = { path = "../api" }
console_commands = { path = "../console_commands" }
